/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.NEXT_PUBLIC_AWS_PROJECT_REGION,
    "aws_appsync_graphqlEndpoint": process.env.NEXT_PUBLIC_AWS_APPSYNC_GRAPHQL_ENDPOINT,
    "aws_appsync_region": process.env.NEXT_PUBLIC_AWS_APPSYNC_REGION,
    "aws_appsync_authenticationType": process.env.NEXT_PUBLIC_AWS_APPSYNC_AUTHENTICATION_TYPE,
    "aws_appsync_apiKey": process.env.NEXT_PUBLIC_AWS_APPSYNC_API_KEY,
};


export default awsmobile;
